---
troubleshooting_packages:
- bind-utils
- curl
- ethtool
- iotop
- iproute
- iptstate
- lsof
- ltrace
- man-pages
- numactl
- pcp-system-tools
- perf
- "{{ 'policycoreutils-python-utils' if ansible_facts.distribution_major_version|int >= 8 else 'policycoreutils-python' }}"
- procps-ng
- psmisc
- sos
- strace
- sysstat
- tcpdump
- time
