---
- name: Install cockpit web console packages
  vars:
    cockpit_install:
      - cockpit
      - cockpit-bridge
      - cockpit-system
      - cockpit-ws
      - "{{ 'cockpit-pcp' if web_console_enable_perf_metrics|bool else '' }}"
  yum:
    name: "{{ cockpit_install | select() | list }}"
    state: present
    install_weak_deps: false

- name: Remove cockpit web console packages
  vars:
    cockpit_remove:
      - "{{ 'cockpit-pcp' if not web_console_enable_perf_metrics|bool else '' }}"
  yum:
    name: "{{ cockpit_remove | select() | list }}"
    state: absent
    autoremove: true

- name: Enable cockpit web console
  service:
    name: cockpit.socket
    state: started
    enabled: true

- name: Enable performance metrics monitoring
  service:
    name: pmcd
    state: started
    enabled: true
  when: web_console_enable_perf_metrics | bool

- name: Enable performance metrics archiving
  service:
    name: pmlogger
    state: started
    enabled: true
  when: web_console_enable_perf_metrics | bool
