---
- name: Install required cockpit web console packages
  vars:
    cockpit_install:
      - cockpit
      - cockpit-bridge
      - cockpit-system
      - cockpit-ws
      - "{{ 'cockpit-pcp' if web_console_enable_perf_metrics|bool else '' }}"
  yum:
    name: "{{ cockpit_install | select() | list }}"
    install_weak_deps: false
    state: present

- name: Remove unneeded cockpit web console packages
  vars:
    cockpit_remove:
      - "{{ 'cockpit-pcp' if not web_console_enable_perf_metrics|bool else '' }}"
  yum:
    name: "{{ cockpit_remove | select() | list }}"
    autoremove: true
    #cacheonly: true
    disable_plugin:
      - product-id
      - subscription-manager
    state: absent

- name: Gather package facts
  package_facts:

- name: Enable cockpit web console
  service:
    name: cockpit.socket
    state: started
    enabled: true
  when: "'cockpit' in ansible_facts.packages"

- name: Enable performance metrics monitoring
  service:
    name: pmcd
    state: started
    enabled: true
  when:
    - "'pcp' in ansible_facts.packages"
    - web_console_enable_perf_metrics | bool

- name: Enable performance metrics archiving
  service:
    name: pmlogger
    state: started
    enabled: true
  when:
    - "'pcp' in ansible_facts.packages"
    - web_console_enable_perf_metrics | bool
