---
- name: Install cockpit web console packages
  yum:
    name:
      - cockpit
    state: present

- name: Enable cockpit web console
  service:
    name: cockpit.socket
    state: started
    enabled: true
