---
- name: Leave AD domain
  vars:
    leave_action: "{{ 'delete-computer' if domain_ad_computer_delete_on_leave else 'reset-computer' }}"
  shell: >
    set -o pipefail
    echo '{{ domain_ad_admin_password }}' |
    adcli -v {{ leave_action }}
    --domain={{ domain_ad_domain }}
    --login-user={{ domain_ad_admin_username }}
    --stdin-password
    {{ ansible_facts.fqdn }}
  no_log: true
  when: krb5_keytab.stat.exists

- name: Disable sssd service
  service:
    name: sssd
    enabled: false

- name: Stop sssd service
  service:
    name: sssd
    state: stopped

- name: Disable oddjobd service
  service:
    name: oddjobd
    enabled: false

- name: Stop oddjobd service
  service:
    name: oddjobd
    state: stopped

- name: Remove Kerberos keytab file
  file:
    path: /etc/krb5.keytab
    state: absent
