---
- name: Leave AD domain
  vars:
    leave_action: "{{ 'delete-computer' if domain_ad_leave_computer_delete | bool else 'reset-computer' }}"
  no_log: true
  shell: >
    set -o pipefail ;
    echo '{{ domain_ad_admin_password }}' |
    adcli -v {{ leave_action }}
    --domain={{ domain_ad_domain }}
    --login-user={{ domain_ad_admin_username }}
    --stdin-password
    {{ ansible_facts.fqdn }}
  changed_when: true
  when: krb5_keytab.stat.exists

- name: Disable sssd-kcm socket
  service:
    enabled: false
    name: sssd-kcm.socket
  when: "'sssd-kcm' in ansible_facts.packages"

- name: Disable sssd service
  service:
    enabled: false
    name: sssd
  when: "'sssd' in ansible_facts.packages"

- name: Stop sssd service
  service:
    state: stopped
    name: sssd
  when: "'sssd' in ansible_facts.packages"

- name: Disable oddjobd service
  service:
    enabled: false
    name: oddjobd
  when: "'oddjob-mkhomedir' in ansible_facts.packages"

- name: Stop oddjobd service
  service:
    state: stopped
    name: oddjobd
  when: "'oddjob-mkhomedir' in ansible_facts.packages"

- name: Remove Kerberos keytab file
  file:
    state: absent
    path: /etc/krb5.keytab

- name: Remove SSSD cache files
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - /var/lib/sss/db/cache_{{ domain_ad_domain }}.ldb
    - /var/lib/sss/db/config.ldb
    - /var/lib/sss/db/sssd.ldb
    - /var/lib/sss/db/timestamps_{{ domain_ad_domain }}.ldb
    - /var/lib/sss/secrets/secrets.ldb
  when: domain_ad_leave_sssd_cache_delete | bool
