---
- name: Install required packages
  yum:
    name:
      - adcli
      - krb5-workstation
      - oddjobd-mkhomedir
      - sssd
    state: present

- name: Create Kerberos configuration file
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    mode: '0644'

- name: Create SSSD configuration file
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: '0600'

- name: Discover AD domain configuration
  command: adcli info {{ domain_ad_domain | upper }}
  register: domain_info
  failed_when: false
  changed_when: false

- name: Join AD domain
  command: adcli ...
  when: false and domain_ad_action == 'join'

- name: Leave AD domain
  command: adcli ...
  when: false and domain_ad_action == 'leave'

# XXX Restart only when really needed
- name: Start sssd service
  service:
    name: sssd
    state: restarted
    enabled: true
