---
- name: Install fapolicyd packages
  yum:
    name:
      - fapolicyd
      - fapolicyd-selinux
    state: present

- name: Check rules.d directory
  stat:
    path: /etc/fapolicyd/rules.d
  register: rules_dir

- name: Copy fapolicyd configuration file
  copy:
    src: fapolicyd.conf
    dest: /etc/fapolicyd/fapolicyd.conf
    owner: root
    group: fapolicyd
    mode: '0644'
  register: daemon_config

- name: Copy fapolicyd rules file
  vars:
    rules_file: "{{ '/etc/fapolicyd/fapolicyd.rules' if not rules_dir.stat.exists else '/etc/fapolicyd/rules.d/zz-local.rules' }}"
  copy:
    src: fapolicyd.rules
    dest: "{{ rules_file }}"
    owner: root
    group: fapolicyd
    mode: '0644'
  register: rules_config

- name: Remove old fapolicyd rules file
  file:
    path: /etc/fapolicyd/fapolicyd.rules
    state: absent
  when: rules_dir.stat.exists

- name: Copy fapolicyd trust file
  vars:
    trust_file: "{{ '/etc/fapolicyd/fapolicyd.trust' if not rules_dir.stat.exists else '/etc/fapolicyd/trust.d/zz-local.trust' }}"
  copy:
    src: fapolicyd.trust
    dest: "{{ trust_file }}"
    owner: root
    group: fapolicyd
    mode: '0644'
  register: trust_config

- name: Verify fapolicyd configuration
  command: fapolicyd-cli --check-config
  changed_when: false
  when: rules_dir.stat.exists

- name: Enable fapolicyd service
  service:
    name: fapolicyd
    enabled: true
  when: fapolicyd_setup_enable_service | bool

- name: Start fapolicyd service
  service:
    name: fapolicyd
    state: started
  register: service_start
  when: fapolicyd_setup_enable_service | bool

- name: Apply fapolicyd configuration changes
  service:
    name: fapolicyd
    state: restarted
  when:
    - fapolicyd_setup_enable_service | bool
    - service_start is not changed
    - daemon_config is changed or rules_config is changed or trust_config is changed
