---
- name: Gather package facts
  package_facts:

- name: Disable usbguard service
  service:
    enabled: false
    name: usbguard
  when: "'usbguard' in ansible_facts.packages"

- name: Stop usbguard service
  service:
    state: stopped
    name: usbguard
  when: "'usbguard' in ansible_facts.packages"
