---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Install USBGuard packages
  yum:
    name: usbguard
    state: present

- name: Gather package facts
  package_facts:

- name: Copy reject-all USBGuard configuration file
  copy:
    content: |
      ImplicitPolicyTarget=reject
      PresentDevicePolicy=reject
      PresentControllerPolicy=reject
      InsertedDevicePolicy=reject
      IPCAllowedUsers=not_allowed
      IPCAllowedGroups=not_allowed
    dest: /etc/usbguard/usbguard-daemon.conf
    mode: '0600'
  register: daemon_config_reject
  when: usbguard_setup_policy == 'reject'

- name: Copy custom USBGuard configuration file
  copy:
    src: "{{ usbguard_setup_config_file }}"
    dest: /etc/usbguard/usbguard-daemon.conf
    mode: '0600'
  register: daemon_config_custom
  when:
    - usbguard_setup_policy == 'custom'
    - usbguard_setup_config_file | default(false)

- name: Clear default USBGuard rules file
  copy:
    content: ''
    dest: /etc/usbguard/rules.conf
    mode: '0600'
  register: rules_config_default
  when:
    - ansible_facts.distribution_major_version | int >= 8 or
      usbguard_setup_rules_file is none or
      not usbguard_setup_rules_file

- name: Create custom USBGuard rules file
  vars:
    old_rhel: "{{ true if ansible_facts.distribution_major_version | int < 8 else false }}"
    rules_file: "{{ 'rules.conf' if old_rhel else 'rules.d/zz-ansible.conf' }}"
  template:
    src: "{{ usbguard_setup_rules_file }}"
    dest: /etc/usbguard/{{ rules_file }}
    mode: '0600'
  register: rules_config_custom
  when:
    - usbguard_setup_policy == 'custom'
    - usbguard_setup_rules_file | default(false)

- name: Enable usbguard service
  service:
    name: usbguard
    enabled: true
  when: "'usbguard' in ansible_facts.packages"

- name: Start usbguard service
  service:
    name: usbguard
    state: started
  register: service_start
  when: "'usbguard' in ansible_facts.packages"

- name: Restart usbguard to apply configuration changes
  service:
    name: usbguard
    state: restarted
  when:
    - "'usbguard' in ansible_facts.packages"
    - service_start is not changed
    - daemon_config_reject is changed or
      daemon_config_custom is changed or
      rules_config_default is changed or
      rules_config_custom is changed
