---
# Policy to apply to USB devices
# reject - block and reject all devices
# custom - custom configuration, see below
# allow - disable USBGuard and allow all USB devices
usbguard_setup_policy: reject

# Custom USBGuard configuration file
# If unset default RHEL configuration will be used
usbguard_setup_config_file:

# Custom USBGuard rules file template to use
usbguard_setup_rules_file:

# To completely disable the USB subsystem
# use the usbcore.nousb boot parameter,
# also see usbcore.authorized_default.
