---
- name: Create issue directory
  file:
    path: /etc/issue.d
    state: directory
    mode: '0755'
  when: ansible_facts.distribution_major_version|int >= 8

- name: Create issue file
  vars:
    issue_content: "{{ lookup('template', issue_template) | trim }}"
    issue_path: "{{ '/etc/issue.d/zz-local.issue' if ansible_facts.distribution_major_version|int >= 8 else '/etc/issue' }}"
  template:
    src: "{{ issue_template }}"
    dest: "{{ issue_path }}"
    mode: '0644'
  when: issue_content != 'Placeholder'

- name: Create motd directory
  file:
    path: /etc/motd.d
    state: directory
    mode: '0755'
  when: ansible_facts.distribution_major_version|int > 8

- name: Create motd file
  vars:
    motd_content: "{{ lookup('template', motd_template) | trim }}"
    motd_path: "{{ '/etc/motd.d/zz-local.motd' if ansible_facts.distribution_major_version|int > 8 else '/etc/motd' }}"
  template:
    src: "{{ motd_template }}"
    dest: "{{ motd_path }}"
    mode: '0644'
  when: motd_content != 'Placeholder'
