---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Create issue directory
  file:
    path: /etc/issue.d
    state: directory
    mode: '0755'
  when:
    - ansible_facts.distribution_major_version | int >= 8
    - issue_template | default(false)

- name: Create issue file
  vars:
    issue_path: "{{ '/etc/issue.d/zz-local.issue' if ansible_facts.distribution_major_version | int >= 8 else '/etc/issue' }}"
  template:
    src: "{{ issue_template }}"
    dest: "{{ issue_path }}"
    mode: '0644'
  when: issue_template | default(false)

- name: Create issue.net file
  template:
    src: "{{ issue_template }}"
    dest: /etc/issue.net
    mode: '0644'
  when: issue_template | default(false)

- name: Create motd directory
  file:
    path: /etc/motd.d
    state: directory
    mode: '0755'
  when:
    - ansible_facts.distribution_major_version | int >= 9
    - motd_template | default(false)

- name: Create motd file
  vars:
    motd_path: "{{ '/etc/motd.d/zz-local.motd' if ansible_facts.distribution_major_version | int >= 9 else '/etc/motd' }}"
  template:
    src: "{{ motd_template }}"
    dest: "{{ motd_path }}"
    mode: '0644'
  when: motd_template | default(false)
