---
- name: Configure RHEL systems
  hosts: all
  become: true
  collections:
    - myllynen.rhel_ansible_roles
  vars:
    #
    # accounts_local
    #
    # List of local users to delete
    # NB. Will remove users' home dirs
    accounts_local_users_delete:
    #  - testuser

    # List of local groups to delete
    accounts_local_groups_delete:
    #  - testgroup

    # List of local groups to create
    # Mandatory parameters: name, gid
    accounts_local_groups_create:
    #  - name: testgroup
    #    gid: 12345

    # List of local users to create
    # Mandatory parameters: name, uid
    accounts_local_users_create:
    #  - name: testuser
    #    # This should come from vault
    #    password: ...
    #    uid: 12345
    #    group: testgroup
    #    comment: Test User
    #    home: /home/testuser
    #    shell: /bin/bash
    #    expires: -1

    # Use true if providing crypted values,
    # false to encrypt cleartext passwords.
    accounts_local_password_encrypted: false
    # Seed for password_hash salt value
    accounts_local_password_salt_seed: "{{ inventory_hostname }}"

    # List of supplementary groups for users
    # Mandatory parameters: name, groups, append
    accounts_local_users_groups:
    #  - name: testuser
    #    groups: tcpdump,wheel
    #    append: true

    #
    # accounts_policy
    #
    # Accounts, login, password, PAM policies and profiles
    # All parameters are optional, unset are left untouched

    # Available alternatives in files/
    login_access_config_file:

    # Available alternatives in files/
    login_defs_config_file:

    # Available alternatives in files/
    password_quality_policy:

    # Available custom alternatives in files/
    # Either use a default profile (e.g., "minimal")
    # or a custom one provided (e.g., "custom/test")
    system_auth_profile:
    # Extra parameters for "authselect select" command
    # See the "authselect show <profile>" output for details
    system_auth_select_parameters: without-nullok with-pamaccess

    #
    # aide_setup
    #
    # Enable periodic aide checks from cron,
    # either: hourly, daily, weekly, monthly
    # Use 'disabled' to disable cron checks.
    aide_setup_check_frequency: weekly

    #
    # audit_setup
    #
    # Available alternatives in files/
    audit_setup_rules: local

    #
    # base_packages - list omitted here for brevity
    #

    #
    # boot_parameters
    #
    boot_parameters_enable:
      - quiet

    boot_parameters_disable:
      - debug
      - rhgb

    boot_parameters_timeout: 1

    # Protect boot parameters with password
    # NB. For the time being this should be
    # PBKDF2 hash to allow idempotency, use
    # grub2-mkpasswd-pbkdf2(3) to create one
    # Boot loader username is always 'root'
    # This should come from vault
    #boot_parameters_password:

    # Reboot system after parameter changes
    boot_parameters_reboot: true

    #
    # certificates
    #
    # List of CA bundle files in PEM format
    certificates_ca_files:
    #  - local-ca-bundle.pem

    # Copy CA certs also to /etc/pki/tls/cert
    certificates_copy_certs: false

    #
    # domain_ad
    #
    # Allowed actions: join, leave
    domain_ad_action: join
    domain_ad_domain: example.com

    # These should come from vault
    #domain_ad_admin_username:
    #domain_ad_admin_password:

    domain_ad_computer_precreated: false
    domain_ad_computer_delete_on_leave: true

    #domain_ad_allow_groups: GROUP@example.com

    # Enable or disable running authconfig/authselect
    # If false then setup by this role is not complete
    domain_ad_auth_config_update: true

    # Extra parameters for "authselect select" command
    # See the "authselect show sssd" output for details
    domain_ad_auth_select_parameters: without-nullok with-pamaccess with-mkhomedir

    #
    # etc_hosts
    #
    # /etc/hosts header to always apply (subject to etc_hosts_omit_hosts)
    # This default header matches the most recent Fedora/upstream headers
    etc_hosts_header: |
      # Loopback entries; do not change.
      # For historical reasons, localhost precedes localhost.localdomain:
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

    # List of lines to add to /etc/hosts
    # NB. Other entries will be removed
    etc_hosts_entries:
    #  - 192.168.122.1   gateway.example.com gateway
    #  - 192.168.122.150 bastion.example.com bastion

    # /etc/hosts entries to omit
    # none - do not omit entries
    # ipv4 - omit all IPv4 entries
    # ipv6 - omit all IPv6 entries
    etc_hosts_omit_hosts: none

    #
    # fapolicyd_setup
    #
    # Enable or disable service after configuration
    # to allow testing and verification before use.
    # NB. See ima_evm_setup if planning to use IMA.
    fapolicyd_setup_enable_service: false

    #
    # fips_setup
    #
    # Enable or not FIPS mode
    # Disabling FIPS mode is unsupported
    fips_setup_enable: true

    #
    # firewall
    #
    firewall_enable: true

    # List of ports (80/tcp, 123/udp, ...) or services (cockpit, https, ...)
    # vars/main.yml lists always open ports/services. ssh is always kept open.
    firewall_open_ports:
    #  - 321/udp

    firewall_open_services:
    #  - samba

    # Close unconfigured ports and services
    firewall_close_unconfigured: true

    firewall_default_zone: public

    #
    # ipv6_setup
    #
    # Enable or disable IPv6 using sysctl settings
    # Boot parameter to disable IPv6 will be removed
    # See https://access.redhat.com/solutions/8709
    ipv6_setup_enable: true

    # Either use system-roles.network to configure NM
    # or enable changing NM configuration by this role
    ipv6_setup_configure_nm: true

    #
    # motd_issue
    #
    # No configuration needed

    #
    # multipath_setup
    #
    # Available alternatives in files/
    multipath_setup_config_file: multipath.conf

    # Reboot system after changes
    # multipathd will be restarted if no reboot
    multipath_setup_reboot: true

    #
    # performance_tuning
    #
    tuned_profile: "{{ 'virtual-guest' if ansible_facts.virtualization_role == 'guest' else 'throughput-performance' }}"

    #
    # rescue_image
    #
    # Enable or disable rescue image
    # NB. Rescue images will be created on next kernel install
    rescue_image_enable: false

    #
    # remove_packages - list omitted here for brevity
    #
    # Enable or disable yum module 'autoremove' parameter
    # to remove all "leaf" packages no longer required
    remove_packages_autoremove: true

    #
    # repository_setup - config omitted here for brevity
    #

    #
    # resolver_configuration
    #
    # NetworkManager updates /etc/resolv.conf
    # true - use NM and system-roles.network
    # false - for using below configurations
    resolver_nm_update: true

    resolver_nameservers:
      - 1.1.1.1
      - 8.8.8.8

    resolver_search_domains:
    #  - corp.local
    #  - example.com

    resolver_options:
    #  - rotate
    #  - timeout:1
    #  - attempts:1

    #
    # root_password
    #
    # Use true if providing crypted value,
    # false to encrypt cleartext password.
    root_password_encrypted: false
    # Seed for password_hash salt value
    root_password_salt_seed: "{{ inventory_hostname }}"
    # This should come from vault
    #root_password:

    #
    # security_hardening
    #
    # Verify Secure Boot is enabled
    # Must be enabled on hardware level
    secure_boot_verify: false

    # One of: disabled, integrity, confidentiality
    # NB. Enabling lockdown will prevent using kdump
    kernel_lockdown: disabled

    selinux: enforcing

    crypto_policy: DEFAULT

    #
    # service_state
    #
    # List of services to stop and disable
    # Missing services will be ignored
    service_state_disable:
      - mlocate-updatedb.timer
      - nfs-client.target
      - rpcbind.service
      - rpcbind.socket

    # List of services to enable and start
    # Missing services will be ignored
    service_state_enable:
      - irqbalance.service

    #
    # shell_profile
    #
    # No configuration needed

    #
    # splunk_forwarder
    #
    splunk_user_uid: 4445
    # This should come from vault
    #splunk_user_password_hash:
    splunk_deployment_server: splunk.example.com
    splunk_deployment_server_port: 8089
    splunk_deployment_server_check: true
    # Allowed states: present, latest
    splunk_forwarder_package_state: present

    #
    # sshd_configuration
    #
    # These options will be enabled/updated in config
    sshd_options:
      PermitRootLogin: prohibit-password
      X11Forwarding: "no"

    # These options will be commented out from config
    sshd_options_disable:
      - Banner

    #
    # system_coredump
    #
    # Enable system-wide coredumps
    system_coredump_enable: true

    #
    # system_init
    #
    # Actions to take after initialization
    # reboot - reboot after initialization
    # syslog - write message to system log
    system_init_final_actions:
      - reboot
      - syslog

    #
    # system_keyboard
    #
    system_keyboard: us
    system_font: eurlatgr

    #
    # system_locale
    #
    # Available locale choices:
    # C.UTF-8 - properly supported on RHEL 9+
    # en_US.UTF-8 - supported on all RHEL versions
    # auto - use C.UTF-8 if RHEL 9+ else en_US.UTF-8
    system_locale: auto

    # Reboot system after changes
    system_locale_reboot: true

    #
    # system_reboot
    #
    # Reboot policy
    # never - never reboot
    # when_needed - reboot if needs-restarting says so
    # always - always reboot
    system_reboot_policy: when_needed

    #
    # system_unregister
    #
    # This role unconditionally unregisters a RHEL system from
    # both Red Hat Insights and Red Hat Subscription Management

    #
    # system_update
    #
    # Reboot policy after applying updates
    # never - never reboot even if updates would require reboot
    # when_needed - reboot only when needed (using needs-restarting)
    # when_updated - reboot if updates were installed
    # always - always reboot even if no updates were installed
    system_update_reboot_policy: when_needed

    # Set true to send a report after updating packages
    system_update_report: true

    # Default recipient email address for the report if no
    # host-specific variable 'email' set in the inventory.
    system_update_report_default_recipient: root@localhost

    # Attach PDF version of the report
    # PDFs will be generated on the control host using
    # utilities from enscript and ghostscript packages
    system_update_report_pdf: false

    # Preamble text to include in all generated PDFs
    # <HOST> will be replaced with inventory hostname
    # <OSREL> will be replaced with OS release name
    # <DATE> will be replaced with patching date/time
    # <REBOOT> will be indicate reboot, true or false
    system_update_report_pdf_preamble: |
        System Update Report
        
        
        Server: <HOST>
        Patch date: <DATE>
        OS version: <OSREL>
        Server rebooted: <REBOOT>
        
        
        The following packages were updated:

    #
    # system_update_report_pre
    #
    # Default recipient email address for the report if no
    # host-specific variable 'email' set in the inventory.
    system_update_report_pre_default_recipient: root@localhost

    # Attach PDF version of the report
    # PDFs will be generated on the control host using
    # utilities from enscript and ghostscript packages
    system_update_report_pre_pdf: false

    # Preamble text to include in all generated PDFs
    # <HOST> will be replaced with inventory hostname
    # <OSREL> will be replaced with OS release name
    system_update_report_pre_pdf_preamble: |
        Pending System Update Report
        
        
        Server: <HOST>
        OS version: <OSREL>
        
        
        The following package updates are pending:

    #
    # timesync
    #
    ntp_servers:
      - 0.rhel.pool.ntp.org
      - 1.rhel.pool.ntp.org
      - 2.rhel.pool.ntp.org
      - 3.rhel.pool.ntp.org
      - time.cloudflare.com

    #
    # timezone
    #
    timezone: UTC

    #
    # troubleshooting_packages - list omitted here for brevity
    #

    #
    # usbguard_setup
    #
    # Policy to apply to USB devices
    # reject - block and reject all devices
    # custom - use configurations in files/
    # allow - disable USBGuard and allow all
    usbguard_setup_policy: reject

    # To completely disable the USB subsyste
    # use the usbcore.nousb boot parameter,
    # also see usbcore.authorized_default.

    #
    # watchdog
    #
    watchdog_enable: true

    # Configure systemd watchdog options,
    # see systemd-system.conf(5) for info
    watchdog_runtime_sec: '60s'
    watchdog_reboot_sec: #'10min'
    watchdog_kexec_sec: #'off'
    watchdog_device: #/dev/watchdog0

    #
    # web_console
    #
    web_console_enable_perf_metrics: true

  roles:
    - etc_hosts
    - ipv6_setup
    - resolver_configuration
    #- rhel-system-roles.network
    #- repository_setup
    #- rescue_image
    #- timezone
    - timesync
    - remove_packages
    - boot_parameters
    #- system_keyboard
    - system_locale
    - audit_setup
    #- { role: multipath_setup, when: ansible_facts.virtualization_role != 'guest' }
    #- rhel-system-roles.storage
    #- system_update_report_pre
    #- system_update
    #- aide_setup
    #- accounts_policy
    #- accounts_local
    - base_packages
    - certificates
    #- { role: domain_ad, when: domain_ad_admin_username is defined }
    #- { role: ipaclient, state: present, when: ipaclient_domain is defined }
    ##- ima_evm_setup
    #- fapolicyd_setup
    #- fips_setup
    - firewall
    - watchdog
    #- motd_issue
    - performance_tuning
    - root_password
    - security_hardening
    - service_state
    #- shell_profile
    - sshd_configuration
    #- troubleshooting_packages
    #- usbguard_setup
    #- web_console
    #- splunk_forwarder
    #- system_coredump
    - system_init
    #- system_reboot
