---
- name: Configure RHEL systems
  hosts: all
  become: true
  vars:
    #
    # abrt_setup
    #
    # Enable or disable abrt
    # NB. abrt not available on RHEL 9+
    abrt_setup_enable: true

    abrt_setup_report_fatal_mce_only: true
    abrt_setup_vmcore_move_not_copy: true
    abrt_setup_console_notification: true
    abrt_setup_unpackaged_reports: true
    abrt_setup_sosreport_plugin: true
    abrt_setup_unsigned_reports: true
    abrt_setup_java_connector: true

    # Purge abrt directories on uninstall
    abrt_setup_uninstall_purge: true

    #
    # accounts_local
    #
    # List of local users to delete
    # NB. Will remove users' home dirs
    accounts_local_users_delete:
    #  - testuser

    # List of local groups to delete
    accounts_local_groups_delete:
    #  - testgroup

    # List of local groups to create
    # Mandatory parameters: name, gid
    accounts_local_groups_create:
    #  - name: testgroup
    #    gid: 12345

    # List of local users to create
    # Mandatory parameters: name, uid
    accounts_local_users_create:
    #  - name: testuser
    #    password: $6$s...
    #    uid: 12345
    #    group: testgroup
    #    comment: Test User
    #    home: /home/testuser
    #    shell: /bin/bash
    #    expires: -1

    # List of supplementary groups for users
    # Mandatory parameters: name, groups, append
    accounts_local_users_groups:
    #  - name: testuser
    #    groups: tcpdump,wheel
    #    append: true

    #
    # accounts_policy
    #
    # Accounts, login, password, PAM policies and profiles
    # All settings are optional, unset are not configured

    # Available alternatives in files/
    login_access_config_file:

    # Available alternatives in files/
    login_defs_config_file:

    # Available alternatives in files/
    password_quality_policy: local

    # Available alternatives in files/
    system_auth_profile:
    # Extra parameters for "authselect select" command
    system_auth_select_parameters:

    #
    # aide_setup
    #
    # Enable periodic aide checks from cron,
    # either: hourly, daily, weekly, monthly
    # Use 'disabled' to disable cron checks.
    aide_setup_check_frequency: weekly

    #
    # audit_setup
    #
    # Available alternatives in files/
    audit_setup_rules: local

    #
    # base_packages - list omitted here for brevity
    #

    #
    # boot_parameters
    #
    boot_parameters_enable:
      - quiet

    boot_parameters_disable:
      - debug
      - rhgb

    # Reboot system after changes
    boot_parameters_reboot: true

    #
    # certificates
    #
    # CA bundle file in PEM format
    certificates_ca_file: local-ca-bundle.pem

    #
    # domain_ad
    #
    # Allowed actions: join, leave
    domain_ad_action: join
    domain_ad_domain: example.com

    # These should come from vault
    #domain_ad_admin_username:
    #domain_ad_admin_password:

    domain_ad_computer_precreated: false
    domain_ad_computer_delete_on_leave: true

    #domain_ad_allow_groups: GROUP@example.com

    # Enable or disable running authconfig/authselect
    # If false then setup by this role is not complete
    domain_ad_auth_config_update: true

    #
    # fapolicyd_setup
    #
    # Enable or disable service after configuration
    # to allow testing and verification before use.
    # NB. See ima_evm_setup if planning to use IMA.
    fapolicyd_setup_enable_service: false

    #
    # firewall
    #
    firewall_enable: true

    # List of ports (80/tcp, 123/udp, ...) or services (cockpit, https, ...)
    # vars/main.yml lists always open ports/services. ssh is always kept open.
    firewall_open_ports:
    #  - 321/udp

    firewall_open_services:
    #  - samba

    # Close unconfigured ports and services
    firewall_close_unconfigured: true

    firewall_default_zone: public

    #
    # motd_issue
    #
    # No configuration needed

    #
    # multipath_setup
    #
    # Available alternatives in files/
    multipath_setup_config_file: multipath.conf

    # Reboot system after changes
    # multipathd will be restarted if no reboot
    multipath_setup_reboot: true

    #
    # performance_tuning
    #
    tuned_profile: "{{ 'virtual-guest' if ansible_facts.virtualization_role == 'guest' else 'throughput-performance' }}"

    #
    # remove_packages - list omitted here for brevity
    #

    #
    # root_password
    #
    # This should come from vault
    #root_password:

    #
    # security_hardening
    #
    selinux: enforcing

    crypto_policy: DEFAULT

    # One of: disabled, integrity, confidentiality
    # NB. Enabling lockdown will prevent using kdump
    kernel_lockdown: disabled

    #
    # service_state
    #
    # List of services to stop and disable
    # Missing services will be ignored
    service_state_disable:
      - mlocate-updatedb.timer
      - nfs-client.target
      - rpcbind.service
      - rpcbind.socket

    # List of services to enable and start
    # Missing services will be ignored
    service_state_enable:
      - irqbalance.service

    #
    # shell_profile
    #
    # No configuration needed

    #
    # splunk_forwarder
    #
    splunk_user_uid: 4445
    # This should come from vault
    #splunk_user_password_hash:
    splunk_deployment_server: splunk.example.com
    splunk_deployment_server_port: 8089
    splunk_deployment_server_check: true
    # Allowed states: present, latest
    splunk_forwarder_package_state: present

    #
    # sshd_configuration
    #
    # These options will be enabled/updated in config
    sshd_options:
      PermitRootLogin: prohibit-password
      X11Forwarding: "no"

    # These options will be commented out from config
    sshd_options_disable:
      - Banner

    #
    # system_coredump
    #
    # Enable system-wide coredumps
    system_coredump_enable: true

    #
    # system_init
    #
    # Actions to take after initialization
    # reboot - reboot after initialization
    # syslog - write message to system log
    system_init_final_actions:
      - reboot
      - syslog

    #
    # system_locale
    #
    # Available locale choices:
    # C.UTF-8 - properly supported on RHEL 9+
    # en_US.UTF-8 - supported on all RHEL versions
    # auto - use C.UTF-8 if RHEL 9+ else en_US.UTF-8
    system_locale: auto

    # Reboot system after changes
    system_locale_reboot: true

    #
    # system_timezone
    #
    system_timezone: UTC

    #
    # system_unregister
    #
    # No configuration needed

    #
    # system_update
    #
    # Reboot policy after applying updates
    # never - never reboot even if updates would require reboot
    # when_needed - reboot only when needed (using needs-restarting)
    # when_updated - reboot if updates were installed
    # always - always reboot even if no updates were installed
    system_update_reboot_policy: when_needed

    # Set true to send a report after updating packages
    system_update_report: true

    # Default recipient email address for the report if no
    # host-specific variable 'email' set in the inventory.
    system_update_report_default_recipient: root@localhost

    # Attach PDF version of the report
    # PDFs will be generated on the control host using
    # utilities from enscript and ghostscript packages
    system_update_report_pdf: false

    # Preamble text to include in all generated PDFs
    # <HOST> will be replaced with inventory hostname
    # <OSREL> will be replaced with OS release name
    # <DATE> will be replaced with patching date/time
    # <REBOOT> will be indicate reboot, true or false
    system_update_report_pdf_preamble: |
        System Update Report
        
        
        Server: <HOST>
        Patch date: <DATE>
        OS version: <OSREL>
        Server rebooted: <REBOOT>
        
        
        The following packages were updated:

    #
    # system_update_report_pre
    #
    # Default recipient email address for the report if no
    # host-specific variable 'email' set in the inventory.
    system_update_report_pre_default_recipient: root@localhost

    # Attach PDF version of the report
    # PDFs will be generated on the control host using
    # utilities from enscript and ghostscript packages
    system_update_report_pre_pdf: false

    # Preamble text to include in all generated PDFs
    # <HOST> will be replaced with inventory hostname
    # <OSREL> will be replaced with OS release name
    system_update_report_pre_pdf_preamble: |
        Pending System Update Report
        
        
        Server: <HOST>
        OS version: <OSREL>
        
        
        The following package updates are pending:

    #
    # timesync
    #
    ntp_servers:
      - 0.rhel.pool.ntp.org
      - 1.rhel.pool.ntp.org
      - 2.rhel.pool.ntp.org
      - 3.rhel.pool.ntp.org
      - time.cloudflare.com

    #
    # troubleshooting_packages - list omitted here for brevity
    #

    #
    # web_console
    #
    web_console_enable_perf_metrics: true

  roles:
    #- system_timezone
    - timesync
    - remove_packages
    - boot_parameters
    - system_locale
    - audit_setup
    #- multipath_setup
    #- rhel-system-roles.storage
    #- system_update_report_pre
    #- system_update
    #- abrt_setup
    #- aide_setup
    #- accounts_policy
    #- accounts_local
    - base_packages
    - certificates
    #- domain_ad
    ##- ima_evm_setup
    #- fapolicyd_setup
    - firewall
    #- motd_issue
    - performance_tuning
    - root_password
    - security_hardening
    - service_state
    #- shell_profile
    - sshd_configuration
    #- troubleshooting_packages
    #- web_console
    #- splunk_forwarder
    - system_coredump
    - system_init
