---
namespace: myllynen
name: rhel_ansible_roles
version: "1.4.5"
readme: README.md
authors:
  - Marko Myllynen <myllynen@redhat.com>
description: >
  Ansible roles for RHEL configuration.
license:
  - GPL-3.0-or-later
tags:
  - rhel
  - linux
  - centos
  - configuration
  - infrastructure
dependencies:
  ansible.posix: ">=1.4.0"
  community.general: ">=5.5.0"
repository: https://www.github.com/myllynen/rhel-ansible-roles
issues: https://www.github.com/myllynen/rhel-ansible-roles/issues
