---
# Enable or disable service after configuration
# to allow testing and verification before use.
# NB. See ima_evm_setup if planning to use IMA.
fapolicyd_setup_enable_service: false

# fapolicyd config file to copy, role default ~ RHEL default
fapolicyd_setup_config_file: fapolicyd.conf

# fapolicyd rules file to copy, rules default ~ RHEL default
fapolicyd_setup_rules_file: fapolicyd.rules

# fapolicyd trust file to copy, trust default is empty file
fapolicyd_setup_trust_file: fapolicyd.trust
