---
- name: Stop service
  service:
    name: "{{ item }}"
    state: stopped
  failed_when: false
  loop: "{{ service_state_disable | select() | list }}"

- name: Disable service
  service:
    name: "{{ item }}"
    enabled: false
  failed_when: false
  loop: "{{ service_state_disable | select() | list }}"

- name: Enable service
  service:
    name: "{{ item }}"
    enabled: true
  failed_when: false
  loop: "{{ service_state_enable | select() | list }}"

- name: Start service
  service:
    name: "{{ item }}"
    state: started
  failed_when: false
  loop: "{{ service_state_enable | select() | list }}"
