---
# https://github.com/ansible/ansible/issues/78107
- name: Get list of known systemd units
  check_mode: false
  # noqa: command-instead-of-module
  command: systemctl list-unit-files
  register: unit_files
  changed_when: false

- name: Mask service
  systemd:
    masked: true
    name: "{{ item }}"
  loop: "{{ service_state_mask | select() | list }}"

- name: Unmask service
  systemd:
    masked: false
    name: "{{ item }}"
  loop: "{{ service_state_unmask | select() | list }}"

- name: Disable service
  systemd:
    enabled: false
    name: "{{ item }}"
  loop: "{{ service_state_disable | select() | list }}"
  when: item in unit_files.stdout

- name: Stop service
  systemd:
    state: stopped
    name: "{{ item }}"
  loop: "{{ service_state_disable | select() | list }}"
  when: item in unit_files.stdout

- name: Enable service
  systemd:
    enabled: true
    name: "{{ item }}"
  loop: "{{ service_state_enable | select() | list }}"
  when: not service_state_skip_missing | bool or
        item in unit_files.stdout

- name: Start service
  systemd:
    state: started
    name: "{{ item }}"
  loop: "{{ service_state_enable | select() | list }}"
  when: not service_state_skip_missing | bool or
        item in unit_files.stdout
