---
- name: Gather service facts
  service_facts:

- name: Stop nscd service
  service:
    name: nscd
    state: stopped
  when: "'nscd.service' in ansible_facts.services"

- name: Disable nscd service
  service:
    name: nscd
    enabled: false
  when: "'nscd.service' in ansible_facts.services"
