---
- name: Gather package facts
  package_facts:

- name: Stop nscd service
  service:
    name: nscd
    state: stopped
  when: "'nscd' in ansible_facts.packages"

- name: Disable nscd service
  service:
    name: nscd
    enabled: false
  when: "'nscd' in ansible_facts.packages"
