---
- name: Install nscd package
  yum:
    state: present
    name: nscd

- name: Gather package facts
  package_facts:

- name: Create nscd configuration file
  template:
    src: "{{ dns_cache_nscd_config_file | default('nscd.conf.j2', true) }}"
    dest: /etc/nscd.conf
    mode: '0644'
  register: daemon_config

- name: Enable nscd service
  service:
    enabled: true
    name: nscd
  when: "'nscd' in ansible_facts.packages"

- name: Start nscd service
  service:
    state: started
    name: nscd
  register: service_start
  when: "'nscd' in ansible_facts.packages"

- name: Reload nscd to apply configuration changes
  service:
    state: reloaded
    name: nscd
  when:
    - "'nscd' in ansible_facts.packages"
    - service_start is not changed
    - daemon_config is changed
