---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Install systemd-resolved package
  yum:
    state: present
    name: systemd-resolved
  when: ansible_facts.distribution_major_version | int != 8

- name: Gather service facts
  service_facts:

- name: Enable systemd-resolved service
  service:
    enabled: true
    name: systemd-resolved
  when: "'systemd-resolved.service' in ansible_facts.services"

- name: Start systemd-resolved service
  service:
    state: started
    name: systemd-resolved
  when: "'systemd-resolved.service' in ansible_facts.services"

- name: Update NetworkManager DNS cache configuration
  copy:
    content: |
      [main]
      dns=systemd-resolved
      rc-manager=symlink
    dest: /etc/NetworkManager/conf.d/95-dns-cache.conf
    mode: '0644'
  register: nm_config

- name: Reload NetworkManager to apply configuration changes
  service:
    state: reloaded
    name: NetworkManager
  when: nm_config is changed
