---
- name: Get files
  get_url:
    url: "{{ item.url }}"
    url_username: "{{ item.username | default(omit) }}"
    url_password: "{{ item.password | default(omit) }}"
    use_proxy: "{{ item.use_proxy | default(omit) }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    headers: "{{ item.headers | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
  register: get_files
  loop: "{{ files_get | default([], true) }}"
  loop_control:
    label: "{{ item.dest }}"
