---
- name: Install aide package
  yum:
    name: aide
    state: present

- name: Copy aide-check script
  copy:
    src: aide-check
    dest: /usr/local/sbin/aide-check
    mode: '0755'

- name: Check aide-check script
  stat:
    path: /usr/local/sbin/aide-check
  register: aide_check_script

# Use loop to display the configuration
- name: Enable scheduled aide cron check
  file:
    src: /usr/local/sbin/aide-check
    dest: /etc/cron.{{ item }}/aide-check
    state: link
  loop: "{{ [aide_setup_check_frequency] }}"
  when:
    - aide_check_script.stat.exists
    - aide_setup_check_frequency in ['hourly', 'daily', 'weekly', 'monthly']

- name: Disable unscheduled aide cron checks
  vars:
    cron_remove: "{{ ['hourly', 'daily', 'weekly', 'monthly'] | difference(aide_setup_check_frequency) }}"
  file:
    path: /etc/cron.{{ item }}/aide-check
    state: absent
  loop: "{{ cron_remove }}"
