---
- name: Install tuned package
  yum:
    name: tuned
    state: present

- name: Start tuned service
  service:
    name: tuned
    state: started
    enabled: true

- name: Check current tuned profile
  slurp:
    src: /etc/tuned/active_profile
  register: active_profile

- name: Apply tuned profile
  command: tuned-adm profile {{ tuned_profile }}
  when: active_profile.content|b64decode|trim != tuned_profile
