---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - virtualization_role
  when: ansible_facts.virtualization_role is not defined

- name: Install tuned package
  yum:
    state: present
    name: tuned

- name: Gather package facts
  package_facts:

- name: Enable tuned service
  service:
    enabled: true
    name: tuned
  when: "'tuned' in ansible_facts.packages"

- name: Start tuned service
  service:
    state: started
    name: tuned
  when: "'tuned' in ansible_facts.packages"

- name: Read current tuned profile
  slurp:
    src: /etc/tuned/active_profile
  register: active_profile
  when: "'tuned' in ansible_facts.packages"

- name: Configure tuned profile
  command: tuned-adm profile {{ tuned_profile }}
  changed_when: true
  when:
    - "'tuned' in ansible_facts.packages"
    - active_profile.content | b64decode | trim != tuned_profile
