---
- name: Reset default motd message file
  copy:
    content: ''
    dest: /etc/motd
    mode: '0644'
  when: ansible_facts.distribution_major_version|int >= 8

- name: Create motd configuration directory
  file:
    path: /etc/motd.d
    state: directory
  when: ansible_facts.distribution_major_version|int >= 8

- name: Create motd message file
  vars:
    motd_file: "{{ '/etc/motd.d/zz-local' if ansible_facts.distribution_major_version|int >= 8 else '/etc/motd' }}"
  template:
    src: local.j2
    dest: "{{ motd_file }}"
    mode: '0644'
