---
- name: Reset default motd message
  copy:
    content: ''
    dest: /etc/motd
    mode: '0644'

- name: Create local motd file
  template:
    src: local.j2
    dest: /etc/motd.d/local
    mode: '0644'
