---
galaxy_info:
  role_name: dns_cache
  author: Marko Myllynen <myllynen@redhat.com>
  company: Red Hat, Inc.
  description: dns_cache role
  license: GPLv3+
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
  galaxy_tags:
    - rhel
    - centos
    - configuration
dependencies: []
