---
- name: Update NetworkManager resolver configuration
  vars:
    option_prefix: "{{ '#' if resolver_use_nm | bool else '' }}"
  copy:
    content: |
      [main]
      {{ option_prefix }}rc-manager=unmanaged
    dest: /etc/NetworkManager/conf.d/95-rc-manager.conf
    mode: '0644'
  register: nm_config

- name: Reload NetworkManager to apply configuration changes
  service:
    name: NetworkManager
    state: reloaded
  when: nm_config is changed

- name: Create /etc/resolv.conf file
  vars:
    etc_resolv_conf_content: |
      {% for line in resolver_nameservers | default([], true) %}
      nameserver {{ line }}
      {% endfor %}
      {% if resolver_search_domains %}
      search {{ resolver_search_domains | join(' ') }}
      {% endif %}
      {% if resolver_options %}
      options {{ resolver_options | join(' ') }}
      {% endif %}
  copy:
    content: "{{ etc_resolv_conf_content }}"
    dest: /etc/resolv.conf
    mode: '0644'
  when: not resolver_use_nm | bool
