---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Gather package facts
  package_facts:

- name: Disable rhcd service
  service:
    name: rhcd
    enabled: false
  when: "'rhc' in ansible_facts.packages"

- name: Stop rhcd service
  service:
    name: rhcd
    state: stopped
  when: "'rhc' in ansible_facts.packages"

- name: Unregister system from Red Hat Insights
  command:
    cmd: insights-client --unregister
    removes: /etc/insights-client/.registered
  when: "'insights-client' in ansible_facts.packages"

# Use removes: to only run on registered systems
- name: Clean package manager caches (RHEL 7)
  command:
    cmd: yum -C clean all
    removes: /etc/rhsm/ca/katello-server-ca.pem
  when: ansible_facts.distribution_major_version|int < 8

- name: Unregister from Red Hat Subscription Management
  command: subscription-manager unregister
  register: registration
  failed_when: registration.rc != 0 and 'currently not registered' not in registration.stderr
  changed_when: registration.rc == 0 and 'has been unregistered' in registration.stdout

- name: Remove Katello CA package
  yum:
    name: katello-ca-consumer-*
    autoremove: true
    #cacheonly: true
    disable_plugin:
      - product-id
      - subscription-manager
    disablerepo: '*'
    state: absent

- name: Remove Katello CA certificates
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/rhsm/ca/katello-default-ca.pem
    - /etc/rhsm/ca/katello-server-ca.pem

- name: Locate RHSM cache files
  find:
    paths: /var/lib/rhsm
    recurse: true
    file_type: file
    excludes:
      - redhat.repo
      - syspurpose.json
  register: rhsm_cache

- name: Remove RHSM cache files
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ rhsm_cache.files | map(attribute='path') | list }}"

- name: Clean package manager caches
  command: dnf -C clean all
  when: ansible_facts.distribution_major_version|int >= 8

- name: Check RHSM configuration backup file
  stat:
    path: /etc/rhsm/rhsm.conf.bak
  register: rhsm_backup

- name: Restore RHSM configuration backup file
  copy:
    src: /etc/rhsm/rhsm.conf.bak
    dest: /etc/rhsm/rhsm.conf
    remote_src: true
  when: rhsm_backup.stat.exists

- name: Remove RHSM configuration backup file
  file:
    path: /etc/rhsm/rhsm.conf.bak
    state: absent
  when: rhsm_backup.stat.exists
