---
- name: Install troubleshooting packages
  yum:
    name: "{{ troubleshooting_packages }}"
    state: present

- name: Enable performance metrics monitoring
  service:
    name: pmcd
    state: started
    enabled: true
  when:
    - troubleshooting_packages_enable_perf_metrics | bool
    - "'pcp-system-tools' in troubleshooting_packages"

- name: Enable performance metrics archiving
  service:
    name: pmlogger
    state: started
    enabled: true
  when:
    - troubleshooting_packages_enable_perf_metrics | bool
    - "'pcp-system-tools' in troubleshooting_packages"
