---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Restore system default coredump limit configuration
  vars:
    option_prefix: "{{ '#' if ansible_facts.distribution_major_version|int < 8 else '' }}"
    option_value: "{{ '' if ansible_facts.distribution_major_version|int < 8 else '0:infinity' }}"
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: '^(#|)DefaultLimitCORE=.*'
    line: '{{ option_prefix }}DefaultLimitCORE={{ option_value }}'
  register: core_config

- name: Reload systemd to apply coredump limit change
  systemd:
    daemon_reload: true
  when: core_config is changed

- name: Disallow suid binary coredumps
  ansible.posix.sysctl:
    name: fs.suid_dumpable
    value: '0'
    sysctl_file: /etc/sysctl.d/50-coredump.conf
    sysctl_set: true
  register: suid_config

- name: Restore system default core pattern
  ansible.posix.sysctl:
    name: kernel.core_pattern
    value: 'core'
    sysctl_file: /etc/sysctl.d/50-coredump.conf
    sysctl_set: true
  register: pattern_config

- name: Rebuild initramfs
  command: dracut -f --regenerate-all
  when: core_config is changed or
        suid_config is changed or
        pattern_config is changed
