---
- name: Configure system core dump pattern
  ansible.posix.sysctl:
    name: kernel.core_pattern
    value: '/var/lib/systemd/coredump/core'
    sysctl_file: /etc/sysctl.d/50-coredump.conf
    sysctl_set: true
  register: pattern_config

- name: Allow safe suid binary coredumps
  ansible.posix.sysctl:
    name: fs.suid_dumpable
    value: '2'
    sysctl_file: /etc/sysctl.d/50-coredump.conf
    sysctl_set: true
  register: suid_config

- name: Update default coredump limit configuration
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: '^(#|)DefaultLimitCORE=.*'
    line: 'DefaultLimitCORE=infinity'
  register: core_config

- name: Reload systemd to apply coredump limit change
  systemd:
    daemon_reload: true
  when: core_config is changed

- name: Rebuild initramfs
  command: dracut -f --regenerate-all
  when: core_config is changed or
        suid_config is changed or
        pattern_config is changed
