---
- name: Enable system-wide coredumps
  include_tasks: enable.yml
  when: system_coredump_enable | bool

- name: Disable system-wide coredumps
  include_tasks: disable.yml
  when: not system_coredump_enable | bool
