---
# Optional auditd config file to copy
# Role provided alternatives:
# * auditd_cis.conf   - CIS Level 2 - Server compliant config
# * auditd_rhel.conf  - RHEL default config
# * auditd_rhel7.conf - RHEL 7 default config
audit_setup_config_file:

# Optional audit rules file to copy
audit_setup_rules_file:

# Action with locked rules if rules changed
# Allowed values: fail, ignore, reboot
audit_setup_update_lock: fail
