---
# These options will be enabled/updated in config
sshd_options:
  PermitRootLogin: prohibit-password
  X11Forwarding: "no"

# These options will be commented out from config
sshd_options_disable:
  - Banner
