---
- name: Unregister from Red Hat Subscription Management
  command: subscription-manager unregister
  register: registration
  failed_when: registration.rc != 0 and 'currently not registered' not in registration.stderr
  changed_when: registration.rc == 0 and 'has been unregistered' in registration.stdout

- name: Remove Katello CA package
  yum:
    name: katello-ca-consumer-*
    autoremove: true
    #cacheonly: true
    disable_plugin:
      - product-id
      - subscription-manager
    state: absent

- name: Remove Katello CA certificates
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/rhsm/ca/katello-default-ca.pem
    - /etc/rhsm/ca/katello-server-ca.pem

- name: Locate RHSM cache files
  find:
    paths: /var/lib/rhsm
    recurse: true
    file_type: file
    excludes:
      - redhat.repo
      - syspurpose.json
  register: rhsm_cache

- name: Remove RHSM cache files
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ rhsm_cache.files | map(attribute='path') | list }}"
