---
- name: Unregister from Red Hat Subscription Management
  command: subscription-manager unregister
  register: registration
  failed_when: registration.rc != 0 and 'currently not registered' not in registration.stderr
  changed_when: registration.rc == 0 and 'has been unregistered' in registration.stdout

- name: Remove Katello CA package
  yum:
    state: absent
    name: katello-ca-consumer-*
    #cacheonly: true
    disable_plugin:
      - product-id
      - subscription-manager
    disablerepo: '*'

- name: Remove Katello CA certificates
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - /etc/rhsm/ca/katello-default-ca.pem
    - /etc/rhsm/ca/katello-server-ca.pem

- name: Locate RHSM cache files
  find:
    paths: /var/lib/rhsm
    recurse: true
    file_type: file
    excludes:
      - redhat.repo
      - syspurpose.json
  register: rhsm_cache

- name: Remove RHSM cache files
  file:
    state: absent
    path: "{{ item }}"
  loop: "{{ rhsm_cache.files | map(attribute='path') | list }}"

- name: Check RHSM configuration backup file
  stat:
    path: /etc/rhsm/rhsm.conf.bak
  register: rhsm_backup

- name: Restore RHSM configuration backup file
  copy:
    src: /etc/rhsm/rhsm.conf.bak
    dest: /etc/rhsm/rhsm.conf
    mode: '0644'
    remote_src: true
  when: rhsm_backup.stat.exists

- name: Remove RHSM configuration backup file
  file:
    state: absent
    path: /etc/rhsm/rhsm.conf.bak
  when: rhsm_backup.stat.exists
