---
watchdog_enable: true

# Configure systemd watchdog options,
# see systemd-system.conf(5) for info
watchdog_runtime_sec: '60s'
watchdog_reboot_sec: #'10min'
watchdog_kexec_sec: #'off'
watchdog_device: #/dev/watchdog0
