---
__ima_packages:
  - attr
  - ima-evm-utils
  - keyutils
  - rpm-plugin-ima

__mok_packages:
  - mokutil

__tpm_packages:
  - tpm2-abrmd
  - tpm2-tools
  - tpm2-tss

__ima_boot_params:
  - evm
  - ima_appraise
  - ima_hash
  - ima_policy
  - ima_template
  - integrity_audit
