---
troubleshooting_tools:
  - bind-utils
  - curl
  - ethtool
  - iotop
  - iproute
  #- iptstate
  - lsof
  #- ltrace
  - man-pages
  #- numactl
  - pcp-system-tools
  #- perf
  - "{{ 'policycoreutils-python-utils' if ansible_facts.distribution_major_version|int >= 8 else 'policycoreutils-python' }}"
  - procps-ng
  - psmisc
  #- setroubleshoot-server
  - sos
  - strace
  - sysstat
  - tcpdump
  - time

# Enable PCP performance metrics as needed
troubleshooting_tools_enable_perf_metrics: true
