---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Install grubby package
  yum:
    name: grubby
    state: present
  when: ansible_facts.distribution_major_version|int >= 8

- name: Enable IMA/EVM
  include_tasks: enable.yml
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - ima_evm_setup_enable | bool

- name: Disable IMA/EVM
  include_tasks: disable.yml
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - not ima_evm_setup_enable | bool
