---
galaxy_info:
  role_name: abrt_setup
  author: Marko Myllynen <myllynen@redhat.com>
  company: Red Hat, Inc.
  description: abrt_setup role
  license: GPLv3+
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - rhel
    - centos
    - configuration
dependencies: []
