---
- name: Gather package facts
  package_facts:

- name: Disable firewalld service
  service:
    enabled: false
    name: firewalld
  when: "'firewalld' in ansible_facts.packages"

- name: Stop firewalld service
  service:
    state: stopped
    name: firewalld
  when: "'firewalld' in ansible_facts.packages"
