---
- name: Install firewalld package
  yum:
    name: firewalld
    state: present

- name: Disallow zone drifting
  replace:
    dest: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting=yes'
    replace: 'AllowZoneDrifting=no'
  register: firewalld_config

- name: Start firewalld service
  service:
    name: firewalld
    state: "{{ 'restarted' if firewalld_config is changed else 'started' }}"
    enabled: yes

- name: Set default zone
  command: firewall-cmd --set-default-zone={{ firewall_default_zone }}
  register: cmd_result
  changed_when: "'ZONE_ALREADY_SET' not in cmd_result.stderr"

- name: Open configured ports in firewall
  firewalld:
    zone: "{{ firewall_default_zone }}"
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ firewall_open_ports.split(',') }}"
  when: firewall_open_ports != ""

- name: Check open ports in firewall
  command: firewall-cmd --zone={{ firewall_default_zone }} --list-ports
  register: open_ports
  changed_when: false

- name: Close unconfigured ports in firewall
  firewalld:
    zone: "{{ firewall_default_zone }}"
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: disabled
  loop: "{{ open_ports.stdout.split(' ') }}"
  when: item not in firewall_open_ports.split(',')

- name: Open configured services in firewall
  firewalld:
    zone: "{{ firewall_default_zone }}"
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ firewall_open_services.split(',') }}"
  when: firewall_open_services != ""

- name: Check open services in firewall
  command: firewall-cmd --zone={{ firewall_default_zone }} --list-services
  register: open_services
  changed_when: false

- name: Close unconfigured services in firewall
  firewalld:
    zone: "{{ firewall_default_zone }}"
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: disabled
  loop: "{{ open_services.stdout.split(' ') }}"
  when: item != "ssh" and item not in firewall_open_services.split(',')
