---
- name: Install grubby package
  yum:
    name: grubby
    state: present

- name: Check boot parameter to disable IPv6
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=.*("| )ipv6.disable(=| |")'
    state: absent
  check_mode: true
  register: boot_param_check
  changed_when: false

- name: Remove IPv6 boot parameter
  command: >
    grubby
    --update-kernel=ALL
    --remove-args="ipv6.disable"
  register: boot_config
  when: boot_param_check.found == 1

- name: Configure IPv6 using sysctl
  vars:
    disable_ipv6: "{{ '0' if ipv6_setup_enable|bool else '1' }}"
  copy:
    content: |
      net.ipv6.conf.all.disable_ipv6 = {{ disable_ipv6 }}
      net.ipv6.conf.default.disable_ipv6 = {{ disable_ipv6 }}
    dest: /etc/sysctl.d/50-ipv6.conf
  register: sysctl_config

- name: Locate NIC ifcfg configuration files
  find:
    paths: /etc/sysconfig/network-scripts
    patterns:
      - 'ifcfg-e*'
      - 'ifcfg-net*'
  register: ifcfg_files
  when: ipv6_setup_configure_nm | bool

- name: Locate NM connection configuration files
  find:
    paths: /etc/NetworkManager/system-connections
    patterns:
      - '*.nmconnection'
  register: nmconnection_files
  when: ipv6_setup_configure_nm | bool

- name: Configure IPv6 in NIC ifcfg configuration files
  vars:
    disable_ipv6: "{{ 'yes' if ipv6_setup_enable|bool else 'no' }}"
  replace:
    path: "{{ item }}"
    regexp: '^IPV6INIT=.*'
    replace: 'IPV6INIT={{ disable_ipv6 }}'
  register: ifcfg_config
  loop: "{{ ifcfg_files.files | map(attribute='path') | list }}"
  when: ipv6_setup_configure_nm | bool

- name: Configure IPv6 in NM connection configuration files
  vars:
    disable_ipv6: "{{ 'auto' if ipv6_setup_enable|bool else 'disabled' }}"
  replace:
    path: "{{ item }}"
    after: '\[ipv6\]'
    before: '\[proxy\]'
    regexp: '^method=.*'
    replace: 'method={{ disable_ipv6 }}'
  register: nmconnection_config
  loop: "{{ nmconnection_files.files | map(attribute='path') | list }}"
  when: ipv6_setup_configure_nm | bool

- name: Rebuild initramfs
  command: dracut -f --regenerate-all
  when: sysctl_config is changed

- name: Reboot system
  reboot:
  when: boot_config is changed or
        sysctl_config is changed or
        ifcfg_config is changed or
        nmconnection_config is changed
