---
# System hostname to be configured in /etc/hostname
#
# Should be short name (not FQDN) when using DHCP,
# FQDN might be better option when using static IP
# but some software will require using short names
system_hostname: "{{ ansible_facts.fqdn | lower }}"
