---
# Enable or disable IPv6 using sysctl settings
# Boot parameter to disable IPv6 will be removed
# See https://access.redhat.com/solutions/8709
ipv6_setup_enable: true

# Some applications (e.g., Samba) require IPv6 stack
# to be enabled to function but need no IPv6 routing
# This option keeps IPv6 on for the loopback device
# This option has effect only when disabling IPv6
ipv6_setup_loopback_persist: false

# Set to true to configure NetworkManager/IPv6 with this role
# When using system_roles.network to configure NM set to false
ipv6_setup_configure_nm: true
