---
# Enable or disable IPv6 using sysctl settings
# Boot parameter to disable IPv6 will be removed
# See https://access.redhat.com/solutions/8709
ipv6_setup_enable: true

# Either use system-roles.network to configure NM
# or enable changing NM configuration by this role
ipv6_setup_configure_nm: true
