---
splunk_deployment_server: splunk.example.com
splunk_deployment_server_port: 8089
splunk_deployment_server_check: true

splunk_user_uid: 4445
# This should come from vault
#splunk_user_password_hash:

splunk_phonehome_secs: 600

# Allowed states: present, latest
splunk_forwarder_package_state: present
