---
splunk_user_uid: 4445
splunk_deployment_server: splunk.example.com
splunk_deployment_server_port: 8089
splunk_deployment_server_check: true
# Allowed states: present, latest
splunk_forwarder_package_state: present
