---
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  register: system_state

- name: Ensure yum-utils installed
  yum:
    name: yum-utils
    state: present
  when: reboot_policy == 'when_needed'

- name: Check need for rebooting
  command: needs-restarting -r
  register: needs_restarting
  failed_when: false
  changed_when: false
  when: reboot_policy == 'when_needed'

- name: Reboot system
  reboot:
  when: (reboot_policy == 'always') or
        (reboot_policy == 'when_updated' and system_state is changed) or
        (reboot_policy == 'when_needed' and needs_restarting.rc != 0)
