---
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_cache: true
  register: system_state

- name: Ensure yum-utils installed
  yum:
    name: yum-utils
    state: present
  when: system_update_reboot_policy == 'when_needed'

- name: Check need for rebooting
  command: needs-restarting -r
  register: needs_restarting
  failed_when: false
  changed_when: false
  when: system_update_reboot_policy == 'when_needed'

- name: Reboot system
  reboot:
  when: (system_update_reboot_policy == 'always') or
        (system_update_reboot_policy == 'when_updated' and system_state is changed) or
        (system_update_reboot_policy == 'when_needed' and needs_restarting.rc != 0)
