---
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_cache: true
  register: package_install

- name: Set package update timestamp
  set_fact:
    patch_time: "{{ '%Y-%m-%d %H:%M:%S %Z' | strftime }}"

- name: Set list of updated packages (RHEL 7)
  set_fact:
    package_updates: "{{ package_install.changes | dict2items | join('\n') }}"
  when: ansible_facts.pkg_mgr == 'yum' and package_install.changes is defined

- name: Set list of updated packages
  set_fact:
    package_updates: "{{ package_install.results | join('\n') }}"
  when: ansible_facts.pkg_mgr == 'dnf' and 'Nothing to do' not in package_install.msg

- name: Display list of updated packages
  debug:
    var: package_updates
  when: package_updates is defined

- name: Install yum-utils package
  yum:
    name: yum-utils
    state: present
  when: system_update_reboot_policy == 'when_needed'

- name: Check need for rebooting
  command: needs-restarting -r
  register: needs_restarting
  failed_when: false
  changed_when: false
  when: system_update_reboot_policy == 'when_needed'

- name: Reboot system
  reboot:
  when: (system_update_reboot_policy == 'always') or
        (system_update_reboot_policy == 'when_updated' and package_install is changed) or
        (system_update_reboot_policy == 'when_needed' and needs_restarting.rc != 0)
  register: system_reboot

- name: Create PDF report
  include_tasks: pdf.yml
  when:
    - system_update_report | bool
    - system_update_report_pdf | bool
    - package_updates is defined

- name: Notify about updated packages
  environment:
    EMAIL_PDF: "{{ system_update_report_pdf }}"
  script: send-notification '{{ hostvars[item].email | default(system_update_report_default_recipient, true) }}' '{{ item }}' '{{ hostvars[item].package_updates }}'
  register: command_output
  delegate_to: localhost
  run_once: true
  become: false
  loop: "{{ ansible_play_batch }}"
  when: system_update_report | bool and hostvars[item].package_updates is defined

- name: Display notification command debug output
  debug:
    msg: "{{ command_output.results | selectattr('item', 'equalto', inventory_hostname) | map(attribute='stdout') | first }}"
  when: system_update_report | bool and hostvars[inventory_hostname].package_updates is defined

- name: Remove local PDF directory
  file:
    path: /tmp/.ansible.pdf
    state: absent
  register: command_output
  delegate_to: localhost
  run_once: true
  become: false
  when: system_update_report_pdf | bool
