---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Install wanted packages
  vars:
    weak_deps: "{{ packages_install_weak_deps | bool if ansible_facts.distribution_major_version | int >= 8 else false }}"
  yum:
    name: "{{ packages_install | select() | list }}"
    install_weak_deps: "{{ weak_deps }}"
    state: present
