---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
      - pkg_mgr
  when: ansible_facts.distribution_major_version is not defined or
        ansible_facts.pkg_mgr is not defined

- name: Install wanted packages
  vars:
    weak_deps: "{{ packages_install_weak_deps | bool if ansible_facts.distribution_major_version | int >= 8 else false }}"
  yum:
    state: present
    name: "{{ packages_install | select() | list }}"
    install_weak_deps: "{{ weak_deps }}"
  register: package_install

- name: Display package changes
  include_tasks: display.yml
  when:
    - packages_install_display_results | bool
    - package_install is changed
