---
- name: Install SELinux packages
  yum:
    name: "{{ selinux_packages }}"
    state: present
  vars:
    selinux_package_lists:
      RedHat_7:
        - libselinux-python
        - libsemanage-python
        - policycoreutils-python
        - selinux-policy-targeted
        - setools-console
      default:
        - python3-libselinux
        - python3-libsemanage
        - policycoreutils-python-utils
        - selinux-policy-targeted
        - setools-console
    distro_id: "{{ ansible_facts.distribution + '_' + ansible_facts.distribution_major_version }}"
    package_set: "{{ 'default' if distro_id not in selinux_package_lists else distro_id }}"
    selinux_packages: "{{ selinux_package_lists[package_set] }}"

- name: Set SELinux state
  selinux:
    policy: targeted
    state: "{{ selinux }}"
  register: selinux_config

- name: Check current crypto policy
  command: update-crypto-policies --show
  register: current_crypto_policy
  changed_when: false

- name: Set crypto policy
  command: update-crypto-policies --set {{ crypto_policy }}
  register: crypto_policy_config
  when: current_crypto_policy is not skipped and current_crypto_policy.stdout != crypto_policy

- name: Reboot system
  reboot:
  when: selinux_config.reboot_required or (current_crypto_policy is not skipped and crypto_policy_config is changed)
