---
# Reboot policy after applying updates
# never - never reboot even if updates would require reboot
# when_needed - reboot only when needed (using needs-restarting)
# when_updated - reboot if updates were installed
# always - always reboot even if no updates were installed
system_update_reboot_policy: when_needed

system_update_report: true
system_update_report_default_recipient: root@localhost
