---
# Allowed actions: join, leave
domain_ad_action: join
domain_ad_domain: example.com
# These should come from vault
#domain_ad_admin_username:
#domain_ad_admin_password:
domain_ad_computer_precreated: false
domain_ad_delete_on_leave: true
#domain_ad_allow_groups: GROUP@example.com
