---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Install grubby package
  yum:
    name: grubby
    state: present

- name: Check enabled boot parameters
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=.*("| ){{ item }}(=| |")'
    state: absent
  check_mode: true
  register: enable_check
  changed_when: false
  loop: "{{ boot_parameters_enable | select() | list }}"

- name: Check disabled boot parameters
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=.*("| ){{ item }}(=| |")'
    state: absent
  check_mode: true
  register: disable_check
  changed_when: false
  loop: "{{ boot_parameters_disable | select() | list }}"

- name: Configure boot parameters
  command: >
    grubby
    --update-kernel=ALL
    --args="{{ boot_parameters_enable | join(' ') }}"
    --remove-args="{{ boot_parameters_disable | join(' ') }}"
  register: boot_config
  when: (0 in enable_check.results | map(attribute='found') | list) or
        (1 in disable_check.results | map(attribute='found') | list)

- name: Fix default kernel boot parameters (RHEL 7)
  shell: |
    eval $(grubby --info=DEFAULT | awk '/^args/ {print $0}')
    sed -i -e "s,^GRUB_CMDLINE_LINUX=.*,GRUB_CMDLINE_LINUX=\"$args\"," /etc/default/grub
  when:
    - ansible_facts.distribution_major_version|int == 7
    - boot_config is changed

- name: Update boot loader timeout configuration
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT=.*'
    replace: 'GRUB_TIMEOUT={{ boot_parameters_timeout }}'
  when:
    - boot_parameters_timeout is integer
    - boot_parameters_timeout | int >= 1
  register: boot_timeout

- name: Determine platform type
  stat:
    path: /sys/firmware/efi
  register: efi_dir

- name: Set boot loader configuration files
  vars:
    old_rhel: "{{ true if ansible_facts.distribution_major_version|int < 9 else false }}"
    efi_path: "{{ true if old_rhel and efi_dir.stat.exists else false }}"
  set_fact:
    grub_config: "{{ '/boot/grub2/grub.cfg' if not efi_path else '/boot/efi/EFI/redhat/grub.cfg' }}"
    user_config: "{{ '/boot/grub2/user.cfg' if not efi_path else '/boot/efi/EFI/redhat/user.cfg' }}"

- name: Update boot loader password configuration
  copy:
    content: |
      GRUB2_PASSWORD={{ boot_parameters_password }}
    dest: "{{ user_config }}"
    mode: '0600'
  register: password_update
  when: boot_parameters_password | default(false)

- name: Remove boot loader password configuration
  file:
    path: "{{ user_config }}"
    state: absent
  register: password_remove
  when: not boot_parameters_password | default(true)

- name: Write boot loader configuration
  command: grub2-mkconfig -o {{ grub_config }}
  when: boot_timeout is changed or
        password_remove is changed or
        password_update is changed

- name: Reboot system
  reboot:
  when:
    - boot_parameters_reboot | bool
    - boot_config is changed
