---
- name: Install grubby package
  yum:
    name: grubby
    state: present

- name: Set list of boot parameters to enable
  set_fact:
    params_enable: "{{ [] if not boot_parameters_enable else boot_parameters_enable.split(' ') | select() | list }}"

- name: Set list of boot parameters to disable
  set_fact:
    params_disable: "{{ [] if not boot_parameters_disable else boot_parameters_disable.split(' ') | select() | list }}"

- name: Check enabled boot parameters
  shell: grep '^GRUB_CMDLINE_LINUX=' /etc/default/grub | grep -Eq '("| ){{ item }}( |")'
  register: enable_check
  loop: "{{ params_enable }}"
  failed_when: false
  changed_when: false

- name: Check disabled boot parameters
  shell: grep '^GRUB_CMDLINE_LINUX=' /etc/default/grub | grep -Eq '("| ){{ item }}( |")'
  register: disable_check
  loop: "{{ params_disable }}"
  failed_when: false
  changed_when: false

- name: Configure boot parameters
  command: >
    grubby
    --update-kernel=ALL
    --args="{{ boot_parameters_enable }}"
    --remove-args="{{ boot_parameters_disable }}"
  register: boot_config
  when: (1 in enable_check.results | map(attribute='rc') | list) or
        (0 in disable_check.results | map(attribute='rc') | list)

- name: Fix default kernel parameters on RHEL 7
  shell: |
    eval $(grubby --info=DEFAULT | awk '/^args/ {print $0}')
    sed -i -e "s,^GRUB_CMDLINE_LINUX=.*,GRUB_CMDLINE_LINUX=\"$args\"," /etc/default/grub
  when: boot_config is changed and ansible_facts.distribution_major_version|int == 7

- name: Reboot system
  reboot:
  when: boot_config is changed and boot_parameters_reboot | bool
