---
- name: Install grubby package
  yum:
    name: grubby
    state: present

- name: Check enabled boot parameters
  vars:
    params_enable: "{{ [] if not boot_parameters_enable else boot_parameters_enable.split(' ') | select() | list }}"
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=.*("| ){{ item }}(=| |")'
    state: absent
  check_mode: true
  register: enable_check
  loop: "{{ params_enable }}"
  changed_when: false

- name: Check disabled boot parameters
  vars:
    params_disable: "{{ [] if not boot_parameters_disable else boot_parameters_disable.split(' ') | select() | list }}"
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=.*("| ){{ item }}(=| |")'
    state: absent
  check_mode: true
  register: disable_check
  loop: "{{ params_disable }}"
  changed_when: false

- name: Configure boot parameters
  command: >
    grubby
    --update-kernel=ALL
    --args="{{ boot_parameters_enable }}"
    --remove-args="{{ boot_parameters_disable }}"
  register: boot_config
  when: (0 in enable_check.results | map(attribute='found') | list) or
        (1 in disable_check.results | map(attribute='found') | list)

- name: Fix default kernel boot parameters (RHEL 7)
  shell: |
    eval $(grubby --info=DEFAULT | awk '/^args/ {print $0}')
    sed -i -e "s,^GRUB_CMDLINE_LINUX=.*,GRUB_CMDLINE_LINUX=\"$args\"," /etc/default/grub
  when: boot_config is changed and ansible_facts.distribution_major_version|int == 7

- name: Reboot system
  reboot:
  when: boot_config is changed and boot_parameters_reboot | bool
