---
- name: Install grubby package
  yum:
    name: grubby
    state: present

- name: Check enabled boot parameters
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=.*("| ){{ item }}(=| |")'
    state: absent
  check_mode: true
  register: enable_check
  loop: "{{ boot_parameters_enable | select() | list }}"
  changed_when: false

- name: Check disabled boot parameters
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=.*("| ){{ item }}(=| |")'
    state: absent
  check_mode: true
  register: disable_check
  loop: "{{ boot_parameters_disable | select() | list }}"
  changed_when: false

- name: Configure boot parameters
  command: >
    grubby
    --update-kernel=ALL
    --args="{{ boot_parameters_enable | join(' ') }}"
    --remove-args="{{ boot_parameters_disable | join(' ') }}"
  register: boot_config
  when: (0 in enable_check.results | map(attribute='found') | list) or
        (1 in disable_check.results | map(attribute='found') | list)

- name: Fix default kernel boot parameters (RHEL 7)
  shell: |
    eval $(grubby --info=DEFAULT | awk '/^args/ {print $0}')
    sed -i -e "s,^GRUB_CMDLINE_LINUX=.*,GRUB_CMDLINE_LINUX=\"$args\"," /etc/default/grub
  when:
    - ansible_facts.distribution_major_version|int == 7
    - boot_config is changed

- name: Reboot system
  reboot:
  when:
    - boot_parameters_reboot | bool
    - boot_config is changed
