---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Install troubleshooting tools
  yum:
    name: "{{ troubleshooting_tools }}"
    state: present

- name: Gather package facts
  package_facts:

- name: Enable performance metrics monitoring
  service:
    name: pmcd
    state: started
    enabled: true
  when:
    - "'pcp' in ansible_facts.packages"
    - troubleshooting_tools_enable_perf_metrics | bool
    - "'pcp-system-tools' in troubleshooting_tools"

- name: Enable performance metrics archiving
  service:
    name: pmlogger
    state: started
    enabled: true
  when:
    - "'pcp' in ansible_facts.packages"
    - troubleshooting_tools_enable_perf_metrics | bool
    - "'pcp-system-tools' in troubleshooting_tools"
