---
- name: Abort if audit disabled on kernel command line
  fail:
    msg: "Audit disabled on kernel command line."
  when: "'audit' in ansible_facts.cmdline and ansible_facts.cmdline['audit'] == '0'"

- name: Install audit package
  yum:
    name: audit
    state: present

- name: Start auditd service
  service:
    name: auditd
    state: started
    enabled: true

- name: Copy audit rules configuration file
  copy:
    src: "{{ audit_setup_rules }}.rules"
    dest: /etc/audit/rules.d/zz-local.rules
    mode: '0600'
  register: rules_config

- name: Copy auditd configuration file
  vars:
    config_files:
      rhel7: "rhel7_auditd.conf"
      default: "default_auditd.conf"
    distro_id: "{{ 'rhel' + ansible_facts.distribution_major_version }}"
    conf_file_id: "{{ 'default' if distro_id not in config_files else distro_id }}"
    config_file: "{{ config_files[conf_file_id] }}"
  copy:
    src: "{{ config_file }}"
    dest: /etc/audit/auditd.conf
    mode: '0600'
  register: auditd_config

# auditd is not compatible with the Ansible service module
- name: Apply audit configuration changes
  command:
    cmd: service auditd reload
    warn: false
  when: rules_config is changed or auditd_config is changed
