---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - cmdline
      - distribution_major_version
  when: ansible_facts.cmdline is not defined or
        ansible_facts.distribution_major_version is not defined

- name: Abort if audit disabled in kernel
  fail:
    msg: "Audit disabled on kernel command line."
  when:
    - "'audit' in ansible_facts.cmdline"
    - ansible_facts.cmdline['audit'] == '0'

- name: Install audit package
  yum:
    name: audit
    state: present

- name: Copy audit rules configuration file
  copy:
    src: "{{ audit_setup_rules_file }}"
    dest: /etc/audit/rules.d/zz-local.rules
    mode: '0600'
  register: rules_config
  when: audit_setup_rules_file | default(false)

- name: Copy auditd configuration file
  vars:
    config_files:
      rhel7: rhel7_auditd.conf
      default: default_auditd.conf
    distro_id: "{{ 'rhel' + ansible_facts.distribution_major_version }}"
    config_id: "{{ 'default' if distro_id not in config_files else distro_id }}"
    config_file: "{{ config_files[config_id] }}"
  copy:
    src: "{{ audit_setup_config_file | default(config_file, true) }}"
    dest: /etc/audit/auditd.conf
    mode: '0640'
  register: auditd_config

- name: Enable auditd service
  service:
    name: auditd
    enabled: true

- name: Start auditd service
  service:
    name: auditd
    state: started
  register: service_start

# auditd is not compatible with the Ansible service module
- name: Reload auditd to apply configuration changes
  command: service auditd reload
  when:
    - service_start is not changed
    - rules_config is changed or
      auditd_config is changed
