---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - cmdline
      - distribution_major_version
  when: ansible_facts.cmdline is not defined or
        ansible_facts.distribution_major_version is not defined

- name: Fail if audit disabled in kernel
  fail:
    msg: "Audit disabled on kernel command line."
  when:
    - "'audit' in ansible_facts.cmdline"
    - ansible_facts.cmdline['audit'] == '0'

- name: Install audit package
  yum:
    name: audit
    state: present

- name: Gather package facts
  package_facts:

- name: Copy auditd configuration file
  vars:
    config_files:
      rhel7: rhel7_auditd.conf
      default: default_auditd.conf
    distro_id: "{{ 'rhel' + ansible_facts.distribution_major_version }}"
    config_id: "{{ 'default' if distro_id not in config_files else distro_id }}"
    config_file: "{{ config_files[config_id] }}"
  copy:
    src: "{{ audit_setup_config_file | default(config_file, true) }}"
    dest: /etc/audit/auditd.conf
    mode: '0640'
  register: auditd_config

- name: Copy audit rules configuration file
  copy:
    src: "{{ audit_setup_rules_file }}"
    dest: /etc/audit/rules.d/zz-local.rules
    mode: '0600'
  register: rules_config
  when: audit_setup_rules_file | default(false)

- name: Enable auditd service
  service:
    name: auditd
    enabled: true
  when: "'audit' in ansible_facts.packages"

- name: Start auditd service
  service:
    name: auditd
    state: started
  register: service_start
  when: "'audit' in ansible_facts.packages"

- name: Check locked audit rules
  command: auditctl -s
  check_mode: false
  register: audit_rules
  changed_when: false
  when: "'audit' in ansible_facts.packages"

- name: Fail if audit rules cannot be updated
  fail:
    msg: "Audit rules are locked."
  when:
    - audit_setup_update_lock == 'fail'
    - "'enabled 2' in audit_rules.stdout"
    - rules_config is changed

# auditd is not compatible with the Ansible service module
# https://github.com/ansible/ansible/issues/22171
# https://access.redhat.com/solutions/2664811
- name: Reload auditd to apply configuration changes
  command: service auditd reload
  when:
    - "'audit' in ansible_facts.packages"
    - "'enabled 2' not in audit_rules.stdout or
      (auditd_config is changed and rules_config is not changed)"
    - "'enabled 2' not in audit_rules.stdout or
      audit_setup_update_lock != 'reboot'"
    - service_start is not changed
    - auditd_config is changed or
      rules_config is changed

- name: Reboot system
  reboot:
  when:
    - "'audit' in ansible_facts.packages"
    - audit_setup_update_lock == 'reboot'
    - "'enabled 2' in audit_rules.stdout"
    - rules_config is changed
