---
- name: Gather package facts
  package_facts:

- name: Disable rhcd service
  service:
    name: rhcd
    enabled: false
  when: "'rhc' in ansible_facts.packages"

- name: Stop rhcd service
  service:
    name: rhcd
    state: stopped
  when: "'rhc' in ansible_facts.packages"

- name: Unregister system from Red Hat Insights
  command:
    cmd: insights-client --unregister
    removes: /etc/insights-client/.registered
  when: "'insights-client' in ansible_facts.packages"
