---
- name: Enable Red Hat Insights
  include_tasks: enable.yml
  when: insights_client_register | bool

- name: Disable Red Hat Insights
  include_tasks: disable.yml
  when: not insights_client_register | bool
