---
- name: Install yum-utils package
  yum:
    name: yum-utils
    state: present
  when: system_reboot_policy == 'when_needed'

- name: Gather package facts
  package_facts:

- name: Check need for rebooting
  command: needs-restarting --disableplugin=product-id,subscription-manager -r
  check_mode: false
  register: needs_restarting
  failed_when: false
  changed_when: false
  when:
    - "'yum-utils' in ansible_facts.packages"
    - system_reboot_policy == 'when_needed'

- name: Reboot system
  reboot:
  when: (system_reboot_policy == 'always') or
        (system_reboot_policy == 'when_needed' and needs_restarting.rc is defined and needs_restarting.rc != 0)
