---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - system
  when: ansible_facts.hostname is not defined or
        ansible_facts.domain is not defined or
        ansible_facts.fqdn is not defined

- name: Configure system hostname
  hostname:
    name: "{{ system_hostname }}"
    use: systemd
  register: hostname_config
  when:
    - "':' not in system_hostname"
    - system_hostname | regex_search('[a-zA-Z]')

- name: Rebuild initramfs
  command: dracut -f --regenerate-all
  when: hostname_config is changed
