---
- name: Configure system hostname
  hostname:
    name: "{{ system_hostname }}"
    use: systemd
  register: hostname_config
  when:
    - "'.' in system_hostname"
    - "':' not in system_hostname"
    - system_hostname | regex_search('[a-zA-Z]')

- name: Rebuild initramfs
  command: dracut -f --regenerate-all
  when: hostname_config is changed
