---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Enable abrt
  include_tasks: enable.yml
  when:
    - ansible_facts.distribution_major_version|int < 9
    - abrt_setup_enable | bool

- name: Disable abrt
  include_tasks: disable.yml
  when:
    - ansible_facts.distribution_major_version|int < 9
    - not abrt_setup_enable | bool
