---
# Enable or disable abrt
# NB. abrt not available on RHEL 9+
abrt_setup_enable: true

abrt_setup_report_fatal_mce_only: true
abrt_setup_vmcore_move_not_copy: true
abrt_setup_console_notification: true
abrt_setup_unpackaged_reports: true
abrt_setup_sosreport_plugin: true
abrt_setup_unsigned_reports: true
abrt_setup_java_connector: true

# Purge abrt directories on uninstall
abrt_setup_uninstall_purge: true
