---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Create system-local login access file
  template:
    src: "{{ login_access_config_file }}"
    dest: /etc/security/access.conf
    mode: '0644'
  when: login_access_config_file | default(false)

- name: Create system-local login defaults file
  template:
    src: "{{ login_defs_config_file }}"
    dest: /etc/login.defs
    mode: '0644'
  when: login_defs_config_file | default(false)

- name: Create system-local password quality requirements file (RHEL 7)
  template:
    src: "{{ pwquality_config_file }}"
    dest: /etc/security/pwquality.conf
    mode: '0644'
  when:
    - ansible_facts.distribution_major_version|int < 8
    - pwquality_config_file | default(false)

- name: Create system-local password quality requirements file
  template:
    src: "{{ pwquality_config_file }}"
    dest: /etc/security/pwquality.conf.d/zz-local.conf
    mode: '0644'
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - pwquality_config_file | default(false)

# https://bugzilla.redhat.com/show_bug.cgi?id=2055604
- name: Ensure system-local password quality requirements
  template:
    src: pwquality_conf.rhel{{ ansible_facts.distribution_major_version }}_default.j2
    dest: /etc/security/pwquality.conf
    mode: '0644'
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - pwquality_config_file | default(false)

- name: Install authselect package
  yum:
    name: authselect
    state: present
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - system_auth_profile | default(false)

- name: Gather package facts
  package_facts:

- name: Copy custom authentication profile
  copy:
    src: "{{ system_auth_profile.replace('custom/', '') }}"
    dest: /etc/authselect/custom
    mode: '0644'
  register: custom_profile_copy
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - system_auth_profile | default(false)
    - system_auth_profile.startswith('custom/')

- name: Check current system-local authentication profile in use
  command: authselect current -r
  check_mode: false
  register: profile_current
  failed_when: profile_current.rc != 0 and 'No existing configuration' not in profile_current.stdout
  changed_when: false
  when:
    - "'authselect' in ansible_facts.packages"
    - ansible_facts.distribution_major_version|int >= 8
    - system_auth_profile | default(false)

- name: Check current system-local authentication profile status
  command: authselect check
  check_mode: false
  register: profile_valid
  failed_when: false
  changed_when: false
  when:
    - "'authselect' in ansible_facts.packages"
    - ansible_facts.distribution_major_version|int >= 8
    - system_auth_profile | default(false)
    - "'No existing configuration' not in profile_current.stdout"

- name: Configure system-local authentication profile
  vars:
    current_config: "{{ profile_current.stdout }}"
    wanted_config: "{{ system_auth_profile }} {{ system_auth_select_parameters }}"
  command: authselect select -f {{ system_auth_profile }} {{ system_auth_select_parameters }}
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - system_auth_profile | default(false)
    - current_config | trim != wanted_config | trim or
      'not valid' in profile_valid.stdout or
      custom_profile_copy is changed
