---
- name: Configure system-local login access
  copy:
    src: access_conf.{{ login_access_config_file }}
    dest: /etc/security/access.conf
    mode: '0644'
  when: login_access_config_file | default(false)

- name: Configure system-local login defaults
  copy:
    src: login_defs.{{ login_defs_config_file }}
    dest: /etc/login.defs
    mode: '0644'
  when: login_defs_config_file | default(false)

- name: Configure system-local password quality requirements (RHEL 7)
  copy:
    src: pwquality_conf.{{ password_quality_policy }}
    dest: /etc/security/pwquality.conf
    mode: '0644'
  when:
    - ansible_facts.distribution_major_version|int < 8
    - password_quality_policy | default(false)

- name: Configure system-local password quality requirements
  copy:
    src: pwquality_conf.{{ password_quality_policy }}
    dest: /etc/security/pwquality.conf.d/zz-local.conf
    mode: '0644'
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - password_quality_policy | default(false)

# https://bugzilla.redhat.com/show_bug.cgi?id=2055604
- name: Ensure system-local password quality requirements
  copy:
    src: pwquality_conf.rhel{{ ansible_facts.distribution_major_version }}_default
    dest: /etc/security/pwquality.conf
    mode: '0644'
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - password_quality_policy | default(false)

- name: Install authselect package
  yum:
    name: authselect
    state: present
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - system_auth_profile | default(false)

- name: Copy system-local authentication profile template
  copy:
    src: auth_profile_{{ system_auth_profile }}
    dest: /etc/authselect/custom
  register: auth_profile_copy
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - system_auth_profile | default(false)

- name: Configure system-local authentication
  command: authselect select -f custom/auth_profile_{{ system_auth_profile }} {{ system_auth_select_parameters }}
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - system_auth_profile | default(false)
    - auth_profile_copy is changed
