---
- name: Configure system-local login access
  copy:
    src: access_conf.{{ login_access_config_file }}
    dest: /etc/security/access.conf
    mode: '0644'
  when: login_access_config_file | default(false)

- name: Configure system-local login defaults
  copy:
    src: login_defs.{{ login_defs_config_file }}
    dest: /etc/login.defs
    mode: '0644'
  when: login_defs_config_file | default(false)

- name: Configure system-local password quality requirements (RHEL 7)
  copy:
    src: pwquality_conf.{{ password_quality_policy }}
    dest: /etc/security/pwquality.conf
    mode: '0644'
  when:
    - ansible_facts.distribution_major_version|int < 8
    - password_quality_policy | default(false)

- name: Configure system-local password quality requirements
  copy:
    src: pwquality_conf.{{ password_quality_policy }}
    dest: /etc/security/pwquality.conf.d/zz-local.conf
    mode: '0644'
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - password_quality_policy | default(false)

# https://bugzilla.redhat.com/show_bug.cgi?id=2055604
- name: Ensure system-local password quality requirements
  copy:
    src: pwquality_conf.rhel{{ ansible_facts.distribution_major_version }}_default
    dest: /etc/security/pwquality.conf
    mode: '0644'
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - password_quality_policy | default(false)

- name: Install authselect package
  yum:
    name: authselect
    state: present
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - system_auth_profile | default(false)

- name: Check current system-local authentication profile
  command: authselect current -r
  register: current_profile
  failed_when: current_profile.rc != 0 and "No existing configuration" not in current_profile.stdout
  changed_when: false
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - system_auth_profile | default(false)

- name: Copy custom authentication profile template
  copy:
    src: "{{ system_auth_profile.replace('custom/', '') }}"
    dest: /etc/authselect/custom
  register: auth_profile_copy
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - system_auth_profile | default(false)
    - system_auth_profile.startswith('custom/')

- name: Configure system-local authentication profile
  command: authselect select -f {{ system_auth_profile }} {{ system_auth_select_parameters }}
  when:
    - ansible_facts.distribution_major_version|int >= 8
    - system_auth_profile | default(false)
    - system_auth_profile not in current_profile.stdout or
      auth_profile_copy is changed
