---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Create system-local new user defaults file
  template:
    src: "{{ useradd_defaults_file }}"
    dest: /etc/default/useradd
    mode: '0644'
  when: useradd_defaults_file | default(false)

- name: Create system-local login defaults file
  template:
    src: "{{ login_defs_config_file }}"
    dest: /etc/login.defs
    mode: '0644'
  when: login_defs_config_file | default(false)

- name: Create system-local login access file
  template:
    src: "{{ login_access_config_file }}"
    dest: /etc/security/access.conf
    mode: '0644'
  when: login_access_config_file | default(false)

- name: Create system-local faillock configuration file
  template:
    src: "{{ faillock_config_file }}"
    dest: /etc/security/faillock.conf
    mode: '0644'
  when:
    - ansible_facts.distribution_major_version | int > 7
    - faillock_config_file | default(false)

- name: Create system-local password history requirements file
  template:
    src: "{{ pwhistory_config_file }}"
    dest: /etc/security/pwhistory.conf
    mode: '0644'
  when:
    - ansible_facts.distribution_major_version | int > 7
    - pwhistory_config_file | default(false)

- name: Create system-local password quality requirements file
  template:
    src: "{{ pwquality_config_file }}"
    dest: /etc/security/pwquality.conf
    mode: '0644'
  when: pwquality_config_file | default(false)

- name: Create system-local user resource limits configuration file
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.d/95-ansible.conf
    mode: '0644'
  when: user_resource_limits is defined

- name: Install required packages
  vars:
    auth_packages:
      - authselect
      - "{{ 'oddjob-mkhomedir' if 'with-mkhomedir' in system_auth_profile_parameters | default('', true) else '' }}"
  yum:
    state: present
    name: "{{ auth_packages | select() | list }}"
  when:
    - ansible_facts.distribution_major_version | int >= 8
    - system_auth_profile | default(false)

- name: Gather package facts
  package_facts:

- name: Enable oddjobd service
  service:
    enabled: true
    name: oddjobd
  when:
    - "'oddjob-mkhomedir' in ansible_facts.packages"
    - "'with-mkhomedir' in system_auth_profile_parameters | default('', true)"

- name: Start oddjobd service
  service:
    state: started
    name: oddjobd
  when:
    - "'oddjob-mkhomedir' in ansible_facts.packages"
    - "'with-mkhomedir' in system_auth_profile_parameters | default('', true)"

- name: Copy custom authentication profile
  copy:
    src: "{{ system_auth_profile }}"
    dest: /etc/authselect/custom
    mode: '0644'
  register: custom_profile_copy
  when:
    - ansible_facts.distribution_major_version | int >= 8
    - system_auth_profile | default(false)
    - "'custom/' in system_auth_profile"

- name: Check current system-local authentication profile in use
  check_mode: false
  command: authselect current -r
  register: profile_current
  failed_when: profile_current.rc != 0 and 'No existing configuration' not in profile_current.stdout
  changed_when: false
  when:
    - "'authselect' in ansible_facts.packages"
    - ansible_facts.distribution_major_version | int >= 8
    - system_auth_profile | default(false)

- name: Check current system-local authentication profile status
  check_mode: false
  command: authselect check
  register: profile_valid
  failed_when: false
  changed_when: false
  when:
    - "'authselect' in ansible_facts.packages"
    - ansible_facts.distribution_major_version | int >= 8
    - system_auth_profile | default(false)
    - "'No existing configuration' not in profile_current.stdout"

- name: Prevent Centrify updating NSS configuration
  lineinfile:
    path: /etc/centrifydc/centrifydc.conf
    regexp: '^(|#|# )adclient.autoedit.nss:.*'
    line: 'adclient.autoedit.nss: false'
  when: "'with-centrify' in system_auth_profile_parameters | default('', true)"

- name: Prevent Centrify updating PAM configuration
  lineinfile:
    path: /etc/centrifydc/centrifydc.conf
    regexp: '^(|#|# )adclient.autoedit.pam:.*'
    line: 'adclient.autoedit.pam: false'
  when: "'with-centrify' in system_auth_profile_parameters | default('', true)"

- name: Configure system-local authentication profile
  vars:
    profile_name: "{{ system_auth_profile | regex_replace('.*custom/', 'custom/') }}"
    current_config: "{{ profile_current.stdout }}"
    wanted_config: "{{ profile_name }} {{ system_auth_profile_parameters }}"
  command: authselect select -f {{ profile_name }} {{ system_auth_profile_parameters }}
  changed_when: true
  when:
    - ansible_facts.distribution_major_version | int >= 8
    - system_auth_profile | default(false)
    - current_config | trim != wanted_config | trim or
      'not valid' in profile_valid.stdout or
      custom_profile_copy is changed

- name: Create PAM su configuration file
  vars:
    enable_centrify: "{{ true if 'with-centrify' in system_auth_profile_parameters | default('', true) else false }}"
  template:
    src: "{{ system_auth_pam_d_su_file }}"
    dest: /etc/pam.d/su
    mode: '0644'
  when: system_auth_pam_d_su_file | default(false)
