---
galaxy_info:
  role_name: files_fetch
  author: Marko Myllynen <myllynen@redhat.com>
  company: Red Hat, Inc.
  description: files_fetch role
  license: GPLv3+
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
  galaxy_tags:
    - rhel
    - centos
    - configuration
dependencies: []

allow_duplicates: true
