---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
      - virtualization_role
      - virtualization_type
  when: ansible_facts.distribution_major_version is not defined or
        ansible_facts.virtualization_role is not defined or
        ansible_facts.virtualization_type is not defined

- name: Remove unneeded firmware packages
  vars:
    firmware_packages:
      - 'a*firmware*'
      - 'i*firmware*'
      - 'lib*firmware*'
      - 'n*firmware*'
      - "{{ 'linux-firmware-whence' if ansible_facts.distribution_major_version | int >= 9 else '' }}"
  yum:
    state: absent
    name: "{{ firmware_packages | select() | list }}"
    #cacheonly: true
  when:
    - ansible_facts.virtualization_role == "guest"
    - guest_agent_remove_firmware | bool

- name: Remove all virtual guest packages
  yum:
    state: absent
    name:
      - 'hyperv*'
      - open-vm-tools
      - qemu-guest-agent
      - spice-vdagent
      - WALinuxAgent
    #cacheonly: true
  when: ansible_facts.virtualization_role != "guest" or
        not guest_agent_enable | bool

- name: Remove unneeded packages on Azure/Hyper-V
  yum:
    state: absent
    name:
      - open-vm-tools
      - qemu-guest-agent
      - spice-vdagent
    #cacheonly: true
  when:
    - ansible_facts.virtualization_role == "guest"
    - ansible_facts.virtualization_type == "VirtualPC"
    - guest_agent_enable | bool

- name: Remove unneeded packages on KVM
  yum:
    state: absent
    name:
      - 'hyperv*'
      - open-vm-tools
      - WALinuxAgent
    #cacheonly: true
  when:
    - ansible_facts.virtualization_role == "guest"
    - ansible_facts.virtualization_type == "kvm"
    - guest_agent_enable | bool

- name: Remove unneeded packages on VMware
  yum:
    state: absent
    name:
      - 'hyperv*'
      - qemu-guest-agent
      - spice-vdagent
      - WALinuxAgent
    #cacheonly: true
  when:
    - ansible_facts.virtualization_role == "guest"
    - ansible_facts.virtualization_type == "VMware"
    - guest_agent_enable | bool

- name: Remove unneeded packages on other VMs
  yum:
    state: absent
    name:
      - 'hyperv*'
      - open-vm-tools
      - qemu-guest-agent
      - spice-vdagent
      - WALinuxAgent
    #cacheonly: true
  when:
    - ansible_facts.virtualization_role == "guest"
    - ansible_facts.virtualization_type not in ['kvm', 'VirtualPC', 'VMware']
    - guest_agent_enable | bool

- name: Install virtual guest package
  vars:
    agent_packages:
      kvm: qemu-guest-agent
      VirtualPC:
        - hyperv-daemons
        - WALinuxAgent
      VMware: open-vm-tools
  yum:
    state: present
    name: "{{ agent_packages[ansible_facts.virtualization_type] }}"
  when:
    - ansible_facts.virtualization_role == "guest"
    - ansible_facts.virtualization_type in agent_packages
    - guest_agent_enable | bool

- name: Gather service facts
  service_facts:
  when:
    - ansible_facts.virtualization_role == "guest"
    - ansible_facts.virtualization_type in ['kvm', 'VirtualPC', 'VMware']
    - guest_agent_enable | bool

- name: Enable virtual guest agent service
  vars:
    agent_services:
      kvm: qemu-guest-agent.service
      VirtualPC: waagent.service
      VMware: vmtoolsd.service
  service:
    enabled: true
    name: "{{ agent_services[ansible_facts.virtualization_type] }}"
  when:
    - ansible_facts.virtualization_role == "guest"
    - ansible_facts.virtualization_type in agent_services
    - ansible_facts.virtualization_type in ['kvm', 'VirtualPC', 'VMware']
    - agent_services[ansible_facts.virtualization_type] in ansible_facts.services
    - guest_agent_enable | bool

- name: Start virtual guest agent service
  vars:
    agent_services:
      kvm: qemu-guest-agent.service
      VirtualPC: waagent.service
      VMware: vmtoolsd.service
  service:
    state: started
    name: "{{ agent_services[ansible_facts.virtualization_type] }}"
  when:
    - ansible_facts.virtualization_role == "guest"
    - ansible_facts.virtualization_type in agent_services
    - ansible_facts.virtualization_type in ['kvm', 'VirtualPC', 'VMware']
    - agent_services[ansible_facts.virtualization_type] in ansible_facts.services
    - guest_agent_enable | bool
